/-
This file was edited by Aristotle.

Lean version: leanprover/lean4:v4.24.0
Mathlib version: f897ebcf72cd16f89ab4577d0c826cd14afaafc7
This project request had uuid: 748778be-1db1-4ba2-af55-2ecff706ded4

To cite Aristotle, tag @Aristotle-Harmonic on GitHub PRs/issues, and add as co-author to commits:
Co-authored-by: Aristotle (Harmonic) <aristotle-harmonic@harmonic.fun>

The following was proved by Aristotle:

- lemma foo (x : K) (h : x ≠ 0) : v.valuation K x = 1 ↔
    FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ x) = 0
-/

import Mathlib


open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum nonZeroDivisors

variable
  {R : Type*} [CommRing R] [IsDedekindDomain R]
  (v : HeightOneSpectrum R)
  (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]

noncomputable section AristotleLemmas

/-
The valuation of an integer $r \in R$ is equal to the negative of the count of the prime ideal $v$ in the principal ideal generated by $r$.
-/
open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum nonZeroDivisors

lemma valuation_eq_count_of_integer {R : Type*} [CommRing R] [IsDedekindDomain R]
    (v : HeightOneSpectrum R)
    (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]
    (r : R) (hr : r ≠ 0) :
    v.valuation K (algebraMap R K r) = Multiplicative.ofAdd (- FractionalIdeal.count K v (FractionalIdeal.spanSingleton (nonZeroDivisors R) (algebraMap R K r))) := by
  rw [valuation_of_algebraMap, intValuation_apply, intValuationDef_if_neg _ hr]
  rw [@ofAdd_neg, WithZero.exp_neg]
  push_cast
  refine inv_inj.mpr ?_


  convert IsDedekindDomain.HeightOneSpectrum.intValuationDef_if_neg _ _;
  any_goals exact hr;
  any_goals assumption;
  · simp +decide [ IsDedekindDomain.HeightOneSpectrum.valuation ];
    exact intValuation_apply v;
  · convert FractionalIdeal.count_coe K v _;
    · simp +decide [ FractionalIdeal.spanSingleton ];
    · simp +decide [ hr, Ideal.span_singleton_eq_bot ]

/-
The valuation of an element $x \in K$ is equal to the negative of the count of the prime ideal $v$ in the fractional ideal generated by $x$.
-/
open IsDedekindDomain IsDedekindDomain.HeightOneSpectrum nonZeroDivisors

theorem valuation_eq_count {R : Type*} [CommRing R] [IsDedekindDomain R]
  (v : HeightOneSpectrum R)
  (K : Type*) [Field K] [Algebra R K] [IsFractionRing R K]
  (x : K) (hx : x ≠ 0) :
  v.valuation K x = Multiplicative.ofAdd (- FractionalIdeal.count K v (FractionalIdeal.spanSingleton (nonZeroDivisors R) x)) := by
    -- Write $x = a/b$ where $a \in R$ and $b \in R \setminus \{0\}$.
    obtain ⟨a, b, ha, hb, hx_eq⟩ : ∃ a b : R, b ≠ 0 ∧ x = (algebraMap R K a) / (algebraMap R K b) := by
      obtain ⟨ a, b, ha, hb, hx ⟩ := IsLocalization.mk'_surjective ( nonZeroDivisors R ) x; use a, b; aesop;
    -- By `valuation_eq_count_of_integer`, $v(a) = \text{ofAdd}(- \text{count}(\text{span}(a)))$ and $v(b) = \text{ofAdd}(- \text{count}(\text{span}(b)))$.
    have h_val_a : v.valuation K (algebraMap R K a) = Multiplicative.ofAdd (- FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (algebraMap R K a))) := by
      by_cases ha : a = 0 <;> simp_all +decide [ div_eq_mul_inv ];
      convert valuation_eq_count_of_integer v K a ha using 1
    have h_val_b : v.valuation K (algebraMap R K b) = Multiplicative.ofAdd (- FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (algebraMap R K b))) := by
      convert valuation_eq_count_of_integer v K b ha using 1;
    -- By the properties of the valuation, we have $v(x) = v(a) / v(b)$.
    have h_val_x : v.valuation K ((algebraMap R K a) / (algebraMap R K b)) = v.valuation K (algebraMap R K a) / v.valuation K (algebraMap R K b) := by
      exact?;
    -- By the properties of the count function, we have $\text{count}(\text{span}(x)) = \text{count}(\text{span}(a)) - \text{count}(\text{span}(b))$.
    have h_count_x : FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ ((algebraMap R K a) / (algebraMap R K b))) = FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (algebraMap R K a)) - FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ (algebraMap R K b)) := by
      have h_count_x : FractionalIdeal.spanSingleton R⁰ ((algebraMap R K a) / (algebraMap R K b)) = FractionalIdeal.spanSingleton R⁰ (algebraMap R K a) * (FractionalIdeal.spanSingleton R⁰ (algebraMap R K b))⁻¹ := by
        simp +decide [ div_eq_mul_inv, FractionalIdeal.spanSingleton_mul_spanSingleton ];
      rw [ h_count_x, FractionalIdeal.count_mul ];
      · rw [ FractionalIdeal.count_inv ] ; ring;
      · simp_all +decide [ FractionalIdeal.spanSingleton_eq_zero_iff ];
      · simp +decide [ ha, FractionalIdeal.spanSingleton_eq_zero_iff ];
    rw [ h_val_x, h_val_a, h_val_b, h_count_x ];
    field_simp;
    exact mod_cast by simp +decide [ sub_eq_add_neg, add_comm, add_left_comm, add_assoc ] ;

end AristotleLemmas

lemma foo (x : K) (h : x ≠ 0) : v.valuation K x = 1 ↔
    FractionalIdeal.count K v (FractionalIdeal.spanSingleton R⁰ x) = 0 := by
  have := @valuation_eq_count R _ _ v K _ _ _ x h;
  rw [ this ] ; norm_cast ; aesop;
